const DATA = {
  kpis: [
    { id:'ia', label:'Precisión IA', value:94.2, unit:'%', meta:'≥92%', norma:'ISO 9001', color:'#185FA5',
      detail:'Validado sobre 50 muestras reales en campo (mayo 2026). Modelo corrido en ESP32-CAM con algoritmo de detección de blobs. Supera la meta en 2.2 puntos porcentuales.',
      hist:[{mes:'Abr',v:91},{mes:'May',v:94.2}] },
    { id:'bat', label:'Baterías recuperadas', value:87.5, unit:'%', meta:'≥80%', norma:'ISO 14001', color:'#3B6D11',
      detail:'87.5% de baterías 18650 recuperadas en mayo 2026. Convenio con planta RAEE autorizada en Córdoba. Cumple Ley 24.051. 3 productores participaron activamente.',
      hist:[{mes:'Abr',v:75},{mes:'May',v:87.5}] },
    { id:'agro', label:'Reducción agroquím.', value:41, unit:'%', meta:'≥35%', norma:'ISO 14001', color:'#3B6D11',
      detail:'Reducción promedio del 41% en aplicación de insecticidas en los 3 lotes activos. Roberto Sánchez (50ha maíz): 41%. Carlos Medina (35ha soja): 38%. María López (12ha hortalizas): 44%.',
      hist:[{mes:'Abr',v:32},{mes:'May',v:41}] },
    { id:'sol', label:'Autonomía solar', value:92, unit:'d', meta:'≥90d', norma:'ISO 9001', color:'#185FA5',
      detail:'92 días de autonomía validados en campo sin recarga externa. Panel solar monocristalino 5W + batería 18650 3500mAh. Deep sleep optimizado: 240mA activo / 10μA sleep.',
      hist:[{mes:'Abr',v:88},{mes:'May',v:92}] },
    { id:'cost', label:'Costo/unidad', value:54, unit:'USD', meta:'≤60 USD', norma:'ISO 9001', color:'#854F0B',
      detail:'Costo final de fabricación USD 54 por unidad (BOM mayo 2026). Desglose: electrónica USD 28, impresión 3D USD 12, batería+solar USD 9, ferromonas+accesorios USD 5.',
      hist:[{mes:'Abr',v:57},{mes:'May',v:54}] },
  ],

  normas: [
    { label:'ISO 9001 — Calidad', pct:96, color:'#185FA5', base:'AUD-SYK-2026-01 · 20/05/2026' },
    { label:'ISO 14001 — Ambiente', pct:94, color:'#3B6D11', base:'AUD-SYK-2026-01 · 20/05/2026' },
    { label:'ISO 45001 — SST', pct:91, color:'#BA7517', base:'AUD-SYK-2026-01 · 20/05/2026' },
  ],

  steps: [
    { n:'01', title:'Diseño y Desarrollo', norma:'ISO 9001', color:'#185FA5', bg:'#E6F1FB', tc:'#0C447C',
      desc:'Diseño mecánico, óptico y electrónico. 6 versiones V0.8→V1.3. Cálculos FOV (150mm), resistencia viento (Cd=0.6), térmica (T°<40°C).',
      result:'V1.3 · 94.2% precisión',
      docs:[{l:'SGI-P-03 Procedimiento',t:'9001'},{l:'HIST V0.8→V1.3',t:'ok'}] },
    { n:'02', title:'Compras y Proveedores', norma:'ISO 9001', color:'#5F5E5A', bg:'#F5F5F0', tc:'#2C2C2A',
      desc:'4 proveedores evaluados. Microelectrónica Córdoba 93pts · Motoma 87pts · Filamentos3D 81pts · Insumos Agro 72pts (condicional).',
      result:'7 lotes · 4 proveedores aprobados',
      docs:[{l:'SGI-P-04 Procedimiento',t:'9001'},{l:'BOM Lotes Abr-May',t:'ok'}] },
    { n:'03', title:'Fabricación y Ensamble', norma:'ISO 9001', color:'#5F5E5A', bg:'#F5F5F0', tc:'#2C2C2A',
      desc:'Impresión 3D ASA/PETG ±0.2mm. Ensamble electrónico, etiquetado QR. 4 unidades fabricadas con trazabilidad completa.',
      result:'4 unidades · USD 54',
      docs:[{l:'SGI-P-05 Procedimiento',t:'9001'},{l:'Planilla Trazabilidad',t:'ok'},{l:'Checklist Liberación',t:'9001'}] },
    { n:'04', title:'Verificación y Validación', norma:'ISO 9001', color:'#5F5E5A', bg:'#F5F5F0', tc:'#2C2C2A',
      desc:'Prueba IP65: lluvia 10min, 3/3 aprobadas. Validación IA: 50 muestras reales, 94.2% precisión, producto liberado.',
      result:'IP65 ✓ · IA 94.2% · Liberado',
      docs:[{l:'Reporte IP65 — 3 unidades',t:'ok'},{l:'Validación IA 94.2%',t:'ok'}] },
    { n:'05', title:'Control de NC', norma:'ISO 9001/14001/45001', color:'#854F0B', bg:'#FFF3E6', tc:'#412402',
      desc:'2 NCs detectadas y cerradas. NC-003: deformación techo ASA. NC-007: falsos positivos IA por ángulo del cono. Metodología 5 Porqués.',
      result:'NC-003 ✓ 16/05 · NC-007 ✓ 22/05',
      docs:[{l:'SGI-P-06 Procedimiento',t:'9001'},{l:'NC-003 Deformación ASA',t:'ok'},{l:'NC-007 Falsos positivos',t:'ok'}] },
    { n:'06', title:'Instalación en Campo', norma:'ISO 9001/14001', color:'#5F5E5A', bg:'#F5F5F0', tc:'#2C2C2A',
      desc:'3 unidades instaladas en Villa María. Capacitación obligatoria: 5/5 aprobados. Encuesta post-instalación: 4.7/5.',
      result:'3 en campo · 4.7/5 satisfacción',
      docs:[{l:'Ficha de Instalación',t:'9001'},{l:'CAP 08/05 — 5/5 ✓',t:'ok'},{l:'Encuesta R. Sánchez',t:'ok'}] },
    { n:'07', title:'Monitoreo y Análisis', norma:'ISO 9001/14001/45001', color:'#5F5E5A', bg:'#F5F5F0', tc:'#2C2C2A',
      desc:'Seguimiento semanal por lote. KPIs: IA 94.2%, autonomía 92d, costo USD 54. 191 insectos contados, 2 alertas enviadas.',
      result:'191 insectos · 2 alertas · ✓',
      docs:[{l:'KPIs Abril-Mayo 2026',t:'ok'},{l:'Conteo Plagas R. Sánchez',t:'ok'},{l:'Informe Mensual Mayo',t:'ok'}] },
    { n:'08', title:'Logística Inversa', norma:'ISO 14001', color:'#3B6D11', bg:'#E8F5E0', tc:'#173404',
      desc:'87.5% baterías recuperadas (meta ≥80%). Convenio RAEE Córdoba. Reducción 41% agroquímicos. 3 productores.',
      result:'87.5% baterías · 41% agroquím.',
      docs:[{l:'Plan Logística Inversa',t:'14001'},{l:'Registro LOG Mayo',t:'ok'},{l:'Reducción Agroquímicos',t:'ok'}] },
  ],

  docs: [
    {label:'Manual del SGI',cat:'est',tag:'9001',icon:'book'},
    {label:'Alcance del SGI',cat:'est',tag:'9001',icon:'target'},
    {label:'Política Integrada',cat:'est',tag:'9001',icon:'shield'},
    {label:'Mapa de Procesos',cat:'est',tag:'9001',icon:'sitemap'},
    {label:'Partes Interesadas',cat:'est',tag:'9001',icon:'users'},
    {label:'Riesgos y Oportunidades',cat:'est',tag:'9001',icon:'alert-triangle'},
    {label:'Objetivos + KPIs',cat:'est',tag:'9001',icon:'chart-bar'},
    {label:'P-02 Control Documentos',cat:'proc',tag:'9001',icon:'files'},
    {label:'P-03 Diseño y Desarrollo',cat:'proc',tag:'9001',icon:'cpu'},
    {label:'P-04 Compras',cat:'proc',tag:'9001',icon:'shopping-cart'},
    {label:'P-05 Fabricación',cat:'proc',tag:'9001',icon:'tool'},
    {label:'P-06 No Conformidades',cat:'proc',tag:'9001',icon:'x-circle'},
    {label:'P-09 Emergencias',cat:'proc',tag:'45001',icon:'alert-octagon'},
    {label:'P-10 Auditoría Interna',cat:'proc',tag:'9001',icon:'clipboard-check'},
    {label:'P-11 Revisión Dirección',cat:'proc',tag:'9001',icon:'presentation'},
    {label:'P-12 Capacitación',cat:'proc',tag:'45001',icon:'school'},
    {label:'P-13 Comunicación',cat:'proc',tag:'9001',icon:'message-circle'},
    {label:'MA-07 Aspectos Ambientales',cat:'mat',tag:'14001',icon:'leaf'},
    {label:'MP-08 Peligros SST',cat:'mat',tag:'45001',icon:'shield-alert'},
    {label:'LOG-08 Logística Inversa',cat:'mat',tag:'14001',icon:'recycle'},
    {label:'F-01 No Conformidad',cat:'form',tag:'9001',icon:'file-x'},
    {label:'F-16 Validación IA',cat:'form',tag:'9001',icon:'brain'},
    {label:'F-17 Prueba IP65',cat:'form',tag:'9001',icon:'droplet'},
    {label:'F-22 Checklist Liberación',cat:'form',tag:'9001',icon:'check-square'},
    {label:'F-27 Dashboard Mapa Calor',cat:'form',tag:'9001',icon:'map'},
  ],

  registros: [
    {label:'NC-003 Deformación ASA',cod:'NC-003',fecha:'12/05/2026',resultado:'Perfil impresión corregido',ok:true},
    {label:'NC-007 Falsos positivos IA',cod:'NC-007',fecha:'18/05/2026',resultado:'Cono anti-reflejo 35°',ok:true},
    {label:'EM-001 Exposición feromonas',cod:'EM-001',fecha:'20/05/2026',resultado:'EPP actualizado',ok:true},
    {label:'REV-DIR-2026-01',cod:'REV-01',fecha:'25/05/2026',resultado:'Satisfactorio — 96%',ok:true},
    {label:'AUD-SYK-2026-01',cod:'AUD-01',fecha:'20/05/2026',resultado:'96% — 0 NC mayores',ok:true},
    {label:'CAP Instalación 08/05',cod:'CAP-01',fecha:'08/05/2026',resultado:'5/5 aprobados',ok:true},
    {label:'KPI Abril-Mayo 2026',cod:'KPI-05',fecha:'Mayo 2026',resultado:'IA 94.2% · USD 54',ok:true},
    {label:'LOG Logística Inversa',cod:'LOG-05',fecha:'Mayo 2026',resultado:'87.5% baterías',ok:true},
    {label:'VAL IA 94.2%',cod:'VAL-01',fecha:'20/05/2026',resultado:'Producto liberado',ok:true},
    {label:'IP65 3 unidades',cod:'IP65-01',fecha:'22/05/2026',resultado:'3/3 aprobadas',ok:true},
    {label:'Conteo Plagas R. Sánchez',cod:'CNT-01',fecha:'Mayo 2026',resultado:'191 insectos · 2 alertas',ok:true},
    {label:'Reducción Agroquímicos 41%',cod:'AGRO-05',fecha:'Mayo 2026',resultado:'41% — 3 productores',ok:true},
  ],

  timeline: [
    {fecha:'Mar 2026',titulo:'Inicio del proyecto',desc:'Definición del concepto Synkro-Eye. Primeros bocetos del dispositivo IoT híbrido solar.',icono:'🌱'},
    {fecha:'Abr 2026',titulo:'Versión V1.0',desc:'Primera unidad funcional. ESP32-CAM + carcasa ASA. Autonomía solar inicial: 88 días.',icono:'⚡'},
    {fecha:'01 May',titulo:'Instalación primer dispositivo',desc:'SYK-202604-001 instalado en Roberto Sánchez, Estancia Los Robles, Villa María.',icono:'📍'},
    {fecha:'08 May',titulo:'Capacitación campo',desc:'5 productores capacitados en instalación segura y logística inversa. 5/5 aprobados.',icono:'🎓'},
    {fecha:'12 May',titulo:'NC-003 detectada y cerrada',desc:'Deformación techo ASA por temperatura cama. Corregida en 4 días con perfil ajustado.',icono:'🔧'},
    {fecha:'20 May',titulo:'Auditoría interna AUD-2026-01',desc:'96% de cumplimiento SGI trinorma. 0 no conformidades mayores. Auditora: D\'Orazio Dayana.',icono:'✅'},
    {fecha:'22 May',titulo:'IP65 — 3 unidades aprobadas',desc:'Prueba de lluvia simulada 10 minutos. Las 3 unidades en campo superaron la prueba.',icono:'🌧️'},
    {fecha:'25 May',titulo:'Revisión por la Dirección',desc:'Estado SATISFACTORIO. IA 94.2%, baterías 87.5%, agroquímicos -41%. Producto liberado.',icono:'🏆'},
  ],

  habilidades: [
    'ISO 9001','ISO 14001','ISO 45001','ESP32-CAM','Python','OpenCV',
    'IA Local','IoT','LPWAN','SolidWorks','ASA 3D','IP65',
    'Lean Manufacturing','Kaizen','5S','PDCA','KPIs','Auditoría SGI',
    'Agricultura 4.0','Visión Artificial','Solar','BMS','Trazabilidad QR',
    'Logística Inversa','RAEE','Arduino','FreeRTOS','MQTT','Edge AI',
  ],
};
